    name: mt5_flutter_app
description: Bot MT5 Mobile
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Menggunakan Dio untuk request REST API ke cloud bridge MT5 (seperti MetaApi)
  dio: ^5.4.0
  
  # Menggunakan WebSocket untuk menerima data harga (stream quotes) secara real-time
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
